"""
Common data models.
"""

from dataclasses import dataclass
from collections.abc import Callable, Sequence
from typing import Any


@dataclass(slots=True, frozen=True)
class Trade:
    """
    Standard trade model used across the project.
    """

    id: int
    price: float
    quantity: float
    quote_quantity: float
    timestamp: int
    is_buyer_maker: bool

@dataclass(slots=True, frozen=True)
class Candle:
    """
    OHLCV candle.
    """

    timestamp: int

    open: float
    high: float
    low: float
    close: float

    volume: float

@dataclass(slots=True)
class PlotSeries:
    """
    One drawable series.
    """

    name: str
    values: Sequence[float | None]

    color: str = "tab:blue"
    linewidth: float = 1.2
    linestyle: str = "-"

    plot_type: str = "line"      # line | scatter | bar
    marker: str = "o"

@dataclass(slots=True)
class OverlayIndicator:
    name: str
    values: Sequence[float]

    color: str = "tab:blue"
    linewidth: float = 1.2
    linestyle: str = "-"

    plot_type: str = "line"      # line | scatter
    marker: str = "o"

@dataclass(slots=True)
class PanelIndicator:
    """
    One indicator panel.

    A panel may contain multiple plotted series.
    """

    name: str

    series: list[PlotSeries]

    @property
    def values(self) -> Sequence[float | None]:
        """Values of the first series, kept for single-series compatibility."""

        return self.series[0].values

@dataclass(slots=True, frozen=True)
class IndicatorSpec:
    """
    Indicator configuration used by the pipeline.
    """

    name: str

    func: Callable[..., list[float | None]]

    kwargs: dict[str, Any]

    color: str = "tab:blue"

    linewidth: float = 1.2

    linestyle: str = "-"

    plot_type: str = "line"

    marker: str = "o"

@dataclass(slots=True, frozen=True)
class Signal:
    """
    Trading signal generated by a strategy.
    """

    timestamp: int

    side: str          # BUY | SELL

    price: float

    strategy: str

    reason: str = ""