"""
Common data models.
"""

from dataclasses import dataclass
from collections.abc import Callable, Sequence
from typing import Any


@dataclass(slots=True, frozen=True)
class Trade:
    """
    Standard trade model used across the project.
    """

    id: int
    price: float
    quantity: float
    quote_quantity: float
    timestamp: int
    is_buyer_maker: bool

@dataclass(slots=True, frozen=True)
class Candle:
    """
    OHLCV candle.
    """

    timestamp: int

    open: float
    high: float
    low: float
    close: float

    volume: float

@dataclass(slots=True)
class PlotSeries:
    """
    One drawable series.
    """

    name: str
    values: Sequence[float | None]

    color: str = "tab:blue"
    linewidth: float = 1.2
    linestyle: str = "-"

    plot_type: str = "line"      # line | scatter | bar
    marker: str = "o"

@dataclass(slots=True)
class OverlayIndicator:
    name: str
    values: Sequence[float]

    color: str = "tab:blue"
    linewidth: float = 1.2
    linestyle: str = "-"

    plot_type: str = "line"      # line | scatter
    marker: str = "o"

@dataclass(slots=True)
class PanelIndicator:
    """
    One indicator panel.

    A panel may contain multiple plotted series.
    """

    name: str

    series: list[PlotSeries]

    @property
    def values(self) -> Sequence[float | None]:
        """Values of the first series, kept for single-series compatibility."""

        return self.series[0].values

@dataclass(slots=True, frozen=True)
class IndicatorSpec:
    """
    Indicator configuration used by the pipeline.
    """

    name: str

    func: Callable[..., list[float | None]]

    kwargs: dict[str, Any]

    color: str = "tab:blue"

    linewidth: float = 1.2

    linestyle: str = "-"

    plot_type: str = "line"

    marker: str = "o"

@dataclass(slots=True, frozen=True)
class Signal:
    """
    Trading signal generated by a strategy.
    """

    timestamp: int

    side: str          # BUY | SELL

    price: float

    strategy: str

    score: float
    
    reason: str = ""

@dataclass(slots=True, frozen=True)
class SymbolFilters:
    """
    Trading rules for a symbol, parsed from Tabdeal's exchangeInfo.

    All prices/quantities are in the units Tabdeal's API uses (base asset
    for quantity, quote asset for price/notional).
    """

    symbol: str
    base_asset: str
    quote_asset: str

    tick_size: float        # PRICE_FILTER: minimum price increment
    min_price: float
    max_price: float

    step_size: float        # LOT_SIZE / MARKET_LOT_SIZE: minimum qty increment
    min_qty: float
    max_qty: float

    min_notional: float     # MIN_NOTIONAL: minimum order value (price * qty)

@dataclass(slots=True, frozen=True)
class OrderRequest:
    """
    A fully-sized, exchange-valid order ready to submit.
    """

    symbol: str
    side: str          # BUY | SELL
    type: str          # MARKET | LIMIT

    quantity: float
    price: float | None = None   # required for LIMIT orders

    reason: str = ""

@dataclass(slots=True, frozen=True)
class OrderResult:
    """
    Outcome of attempting to place an order.
    """

    accepted: bool
    order: OrderRequest

    exchange_order_id: int | None = None
    raw_response: dict | None = None
    rejection_reason: str = ""